### ISSUE TITLE
Cause rancher to crash with chart 1.2.4

### ISSUE THREAD

**Issue by springfred** [LogiGear/selenium3-chart#2]
chart: 1.2.4
rancher:v2.5.9

Add https://chart.testarchitect.com to the rancher Catalogs, which will cause rancher to crash after running for a period of time.

`
021/08/05 01:13:15 [INFO] Updating global catalog ta-chart
E0805 01:13:15.480313       8 runtime.go:78] Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error: index out of range [0] with length 0)
goroutine 36208 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x4440f00, 0xc01d1d7c20)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/runtime/runtime.go:74 +0x92
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/runtime/runtime.go:48 +0x82
panic(0x4440f00, 0xc01d1d7c20)
        /usr/local/go/src/runtime/panic.go:969 +0x166
github.com/rancher/rancher/pkg/catalog/manager.(*Manager).traverseAndUpdate(0xc007efef00, 0xc01bab4aa0, 0xc01d1d6280, 0x20, 0xc007709950, 0x1, 0x1)
        /go/src/github.com/rancher/rancher/pkg/catalog/manager/traverse.go:85 +0x3cec
github.com/rancher/rancher/pkg/catalog/manager.(*Manager).Sync(0xc007efef00, 0xc005f06bf8, 0x8, 0xc004533c80, 0xc0029d4a80, 0x7f09287c5108, 0x0, 0x0)
        /go/src/github.com/rancher/rancher/pkg/catalog/manager/catalog_sync.go:58 +0x414
github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3.(*catalogController).AddHandler.func1(0xc005f06bf8, 0x8, 0x46fc800, 0xc004533c80, 0xc026735b00, 0x3, 0x3, 0x0)
        /go/src/github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3/zz_generated_catalog_controller.go:155 +0x63
github.com/rancher/norman/controller.(*genericController).AddHandler.func1(0xc005f06bf8, 0x8, 0x518de80, 0xc004533c80, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/rancher/norman@v0.0.0-20210225010917-c7fd1e24145b/controller/generic_controller.go:62 +0x221
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc0164060c0, 0xc005f06bf8, 0x8, 0x518de80, 0xc004533c80, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210525230756-26f0072e833e/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc001bea300, 0xc005f06bf8, 0x8, 0x518de80, 0xc004533c80, 0xc018fb6e01, 0x0)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210525230756-26f0072e833e/pkg/controller/sharedhandler.go:66 +0x150
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc0009a24d0, 0xc005f06bf8, 0x8, 0xc020dfe480, 0xc026735d50)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210525230756-26f0072e833e/pkg/controller/controller.go:213 +0xd1
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc0009a24d0, 0x3b652a0, 0xc006fe0d50, 0x0, 0x0)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210525230756-26f0072e833e/pkg/controller/controller.go:195 +0xd7
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc0009a24d0, 0x203008)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210525230756-26f0072e833e/pkg/controller/controller.go:172 +0x51
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc0009a24d0)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210525230756-26f0072e833e/pkg/controller/controller.go:161 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc020853690)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc020853690, 0x5162a60, 0xc020dfe990, 0x1, 0xc001f95140)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc020853690, 0x3b9aca00, 0x0, 0x497cc01, 0xc001f95140)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc020853690, 0x3b9aca00, 0xc001f95140)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/lasso/pkg/controller.(*controller).run
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210525230756-26f0072e833e/pkg/controller/controller.go:132 +0x31f
panic: runtime error: index out of range [0] with length 0 [recovered]
        panic: runtime error: index out of range [0] with length 0

goroutine 36208 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/runtime/runtime.go:55 +0x105
panic(0x4440f00, 0xc01d1d7c20)
        /usr/local/go/src/runtime/panic.go:969 +0x166
github.com/rancher/rancher/pkg/catalog/manager.(*Manager).traverseAndUpdate(0xc007efef00, 0xc01bab4aa0, 0xc01d1d6280, 0x20, 0xc007709950, 0x1, 0x1)
        /go/src/github.com/rancher/rancher/pkg/catalog/manager/traverse.go:85 +0x3cec
github.com/rancher/rancher/pkg/catalog/manager.(*Manager).Sync(0xc007efef00, 0xc005f06bf8, 0x8, 0xc004533c80, 0xc0029d4a80, 0x7f09287c5108, 0x0, 0x0)
        /go/src/github.com/rancher/rancher/pkg/catalog/manager/catalog_sync.go:58 +0x414
github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3.(*catalogController).AddHandler.func1(0xc005f06bf8, 0x8, 0x46fc800, 0xc004533c80, 0xc026735b00, 0x3, 0x3, 0x0)
        /go/src/github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3/zz_generated_catalog_controller.go:155 +0x63
github.com/rancher/norman/controller.(*genericController).AddHandler.func1(0xc005f06bf8, 0x8, 0x518de80, 0xc004533c80, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/rancher/norman@v0.0.0-20210225010917-c7fd1e24145b/controller/generic_controller.go:62 +0x221
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc0164060c0, 0xc005f06bf8, 0x8, 0x518de80, 0xc004533c80, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210525230756-26f0072e833e/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc001bea300, 0xc005f06bf8, 0x8, 0x518de80, 0xc004533c80, 0xc018fb6e01, 0x0)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210525230756-26f0072e833e/pkg/controller/sharedhandler.go:66 +0x150
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc0009a24d0, 0xc005f06bf8, 0x8, 0xc020dfe480, 0xc026735d50)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210525230756-26f0072e833e/pkg/controller/controller.go:213 +0xd1
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc0009a24d0, 0x3b652a0, 0xc006fe0d50, 0x0, 0x0)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210525230756-26f0072e833e/pkg/controller/controller.go:195 +0xd7
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc0009a24d0, 0x203008)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210525230756-26f0072e833e/pkg/controller/controller.go:172 +0x51
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc0009a24d0)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210525230756-26f0072e833e/pkg/controller/controller.go:161 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc020853690)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc020853690, 0x5162a60, 0xc020dfe990, 0x1, 0xc001f95140)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc020853690, 0x3b9aca00, 0x0, 0x497cc01, 0xc001f95140)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc020853690, 0x3b9aca00, 0xc001f95140)
        /go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/lasso/pkg/controller.(*controller).run
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210525230756-26f0072e833e/pkg/controller/controller.go:132 +0x31f

`

**Comment by ziyi-bear** [comment]
Does the cluster have enough memory?
